CREATE TRIGGER `prova`.`transferencia_BEFORE_INSERT` BEFORE INSERT ON `transferencia` FOR EACH ROW
BEGIN
	IF(NEW.IDCONTADESTINO IN (SELECT IDCONTA FROM CONTA WHERE ATIVIDADE = '1'))
    THEN IF(NEW.CODAPORTE IS NOT NULL AND
			NEW.IDCONTADESTINO IN (SELECT IDCONTA_MATRIZ FROM contas_matriz_filial) AND
            NEW.IDCONTADESTINO NOT IN (SELECT IDCONTA_FILIAL FROM contas_matriz_filial))
		 THEN INSERT INTO TRANSFERENCIA VALUES (NEW.IDCONTAORIGEM, NEW.IDCONTADESTINO, NEW.QUANTIA, NEW.CODAPORTE);
		 END IF;
         IF(NEW.CODAPORTE IS NULL AND
           (NEW.IDCONTAORIGEM, NEW.IDCONTADESTINO) IN (SELECT IDCONTA_MATRIZ, IDCONTA_FILIAL FROM contas_matriz_filial))
         THEN INSERT INTO TRANSFERENCIA VALUES (NEW.IDCONTAORIGEM, NEW.IDCONTADESTINO, NEW.QUANTIA, NEW.CODAPORTE);
         END IF;
    END IF;
END