CREATE TRIGGER `prova`.`conta_BEFORE_INSERT` BEFORE INSERT ON `conta` FOR EACH ROW
BEGIN
	IF (NEW.CNPJ IN (SELECT CNPJ FROM CONTA WHERE tipoConta = '1'))
		THEN IF (NEW.tipoConta = '1')
        THEN SET NEW.tipoConta = '2';
        END IF;
    INSERT INTO CONTAS_MATRIZ_FILIAL VALUES ((SELECT IDCONTA FROM CONTA WHERE CNPJ = NEW.CNPJ AND tipoConta = '1'), NEW.idConta);
    END IF;
END